### ISSUE TITLE
[Bug]: 1.19.3 Electromancer Crash

### ISSUE THREAD

**Issue by Tyrius1** [Mrbysco/Raided#1]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

44.1.5

### Minecraft version

1.19.3

### Mod version

0.1.1

### Java version

Java 8 361

### Issue Description

I summoned the Electromancer in creative and it crashed when it tried to attack something

### Additional Information

https://pastebin.com/K5LVgDP9

**Comment by Mrbysco** [comment]
Uploading a new jar later today
