### ISSUE TITLE
[Bug]: crashes upon launch on 1.20.4

### ISSUE THREAD

**Issue by nickademas** [Mrbysco/Raided#6]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

neoforge 20.4.158

### Minecraft version

1.20.4

### Mod version

0.1.3

### Java version

17.0.4.1

### Issue Description

A bug happened!

### Additional Information

https://pastebin.com/Jt33JScV

**Comment by Mrbysco** [comment]
Uploaded a new version that fixes this issue
