### ISSUE TITLE
[Bug]: Necromancer

### ISSUE THREAD

**Issue by Krimatoria** [Mrbysco/Raided#7]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.5

### Minecraft version

Minecraft 1.19.2

### Mod version

Raided-1.19.2-0.1.3.jar

### Java version

zulu-17-jre [Zulu Platform x64 Architecture]

### Issue Description

[22Feb2024 03:58:41.135] [Render thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class com.mrbysco.raided.entity.Inquisitor from class com.mrbysco.raided.entity.Necromancer

**Comment by Mrbysco** [comment]
Will be fixed next version

**Comment by Krimatoria** [comment]
Nice
